[package]
name = "gprx"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
description = "Flexible high-performance Gaussian process regression"
repository = "https://github.com/YUKIKEDA/gprx"
readme = "README.md"
keywords = ["gaussian-process", "gpr", "machine-learning"]
categories = ["science", "mathematics"]
publish = false

[lints.rust]
missing_docs = "deny"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
dbg_macro = "deny"
float_cmp = "deny"

[dependencies]
thiserror = "2.0.20"

[dev-dependencies]
dyn-stack = "0.13"
faer = "0.24.4"
